### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by BuiTanDuoc** [carlosdaniiel07/personal-finances#1]
Please add feature:
Filter Movements/Transfers by date (Accounting)
Select From / To and button View.
Thanks

**Comment by carlosdaniiel07** [comment]
> Please add feature:
> Filter Movements/Transfers by date (Accounting)
> Select From / To and button View.
> Thanks

Yes, I'll add a Bank statement view, where you can filter movements (including transfers) by account, accounting date, category and subcategory. You will also able to export the data to a Excel workbook and PDF. 
Thanks!

**Comment by carlosdaniiel07** [comment]
Solved on commit 4e8553d (release 1.0.1)
