### ISSUE TITLE
How to change database to MySQL

### ISSUE THREAD

**Issue by taozixiongtai** [carlosdaniiel07/personal-finances#3]
I added some UNGET packages from mysql.

Modified connection string

SetSqlGenerator ("MySql. Data. MySqlClient", new MySqlMigration SqlGenerator ()) was added.

But SQL Server database was generated when update-database was used

**Comment by carlosdaniiel07** [comment]
Did you change the `providers` section on `Web.config` file?

**Comment by taozixiongtai** [comment]
<provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
 <provider invariantName="MySql.Data.MySqlClient" type="MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6, Version=6.10.8.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d">

I haven't changed it. It's automatically added。

**Comment by taozixiongtai** [comment]
name="DefaultConnection" connectionString="server=localhost;User Id=root;password=password;Persist Security Info=True;database=mysitedb;charset=utf8" providerName="MySql.Data.MySqlClient



Should I delete one?

**Comment by taozixiongtai** [comment]
AutomaticMigrationsEnabled = true;
change it.

**Comment by carlosdaniiel07** [comment]
> AutomaticMigrationsEnabled = true;
> change it.

Is working?

Is also recommend add the annotation below in the DbContext class (
[Reference here](https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework60.html))

`[DbConfigurationType(typeof(MySqlEFConfiguration))]`
